### PR TITLE
Refactor import module to be more adherent to Blenderbim

### PR DESCRIPTION
**Pull request by carlopav**
Just playing a bit with the module to understand how it works and try to change it to be more similar to blenderbim importer so we can benefit of the blenderbim improvements.
@yorikvanhavre feel free to close the PR it if it's too annoying to have the code refactored as soon as it was written :)

PS It still need more work, but i wanted to share it cause i won't have time till next weekend to work on it.

PS Also used more modern object creation: 
`document.addObject('Part::FeaturePython', 'IfcDocument', bb_object.bb_object(), bb_vp_document.bb_vp_document(), False) `

### CODE REVIEW

**Comment by Moult** [comment]
Looks fine to me :) It's just a refactor after all, it should meet the architectural needs of FreeCAD, no need to copy the BlenderBIM Add-on codebase so closely.

**Comment by carlopav** [comment]
@Moult yes, you are right. I was Just thinking that the most similar we are, the easier will be to for contributors to contribute to both projects. I agree that i exagerated a bit :)
In FC we can delegate a lot of functions to the objects themselves, that can handle custom code on recomputed, on deleted, etc.

@yorikvanhavre I mainly was thinking that we can load all the project structure (should be quite fast) instead of having to expand all the tree one object by one and having a placeholder shape Just for the deeper part of the tree (the objects whose children that are not decomposed by others anymore)... With current implementation It looks the placeholder shape Is duplicated across project, site, Building, storeys, ...

**Comment by yorikvanhavre** [comment]
I don't see any problem with this change, but why exactly? My understanding is that you use a class either if you need to instantiate it, or if you want it to be a holder for class methods. In this case it seems none of these two conditions applies. And by mimicking cosmetically but without functionality aren't we risking to cause more perplexity than solve issues? Just wondering...

About the project structure, sure, of course. The idea is to have different import strategies (one single object like now, or structure only, or structure + objects, or structure + objects + aggregates...) but I wanted to have the "expansion" mechanism working first.

**Comment by carlopav** [comment]
That's a good question: i do not exactly know, i really was Just playing with the code and created a pr to share It.
What i like about blenderbim Is that It Is really clear to read the sequence of the import procedure, and also the console messages allows to follow the import step by step.
Anyway i was also curious to know if using a class Is something needed expecially for Blender or could also be in some way a good design strategy for other reasons... @Moult ? Can you share a thought about that?

**Comment by Moult** [comment]
It is almost always a good idea to encapsulate complex functions into a class. Loading IFC data is guaranteed to be a complex function.

Classes let you:

 1. Share state
 2. Delineate private and public methods
 3. Allow for inheritance and override

So I would highly recommend it (whether or not you should copy the class structure of that particular BlenderBIM Add-on import however is another story ... that one evolved rather organically from a legacy import/export as you can tell ... it's not exactly the cleanest)

**Comment by yorikvanhavre** [comment]
I think I get the idea... Indeed we could start by simply creating a host class and transfer the functions then. In the arch multicore importer there is already a cool system to display progress that we can reuse here.

@carlopav this PR has differed much from the current code, and you and me also added bits of in other commits it already. So if you don't mind we can close this PR and start from scratch? However let's keep this open until we have another one ready, so we don't forget about it :)

**Comment by carlopav** [comment]
Yes, no problem. As I wrote it just was an exercise to understand a bit how BlenderBim Importer works. We can close it, don't worry.

**Comment by yorikvanhavre** [comment]
The more I think to this...

* The importer file is actually (at the moment) a collection of tools/functions that do IFC-related operations
* These tools are used both by the importer and also by the FreeCAD objects when they need to perform IFC-related operations
* So if these tools get wrapped into a class, this class will need to be instantiated many times (by the importer, by each object...) without real need for it. This seems very unoptimized
* If these tools become class methods, there is no real point over the current layout, only more hassle (instead of `import ifc_importer; ifc_importer_create_document()` it would become `import ifc_importer; ifc_importer.IfcClass.create_document()`

So I'm thinking of two possible strategies now:

1. We put all the generic IFC tools into a separate module. So we have ifc_import which just does the initial import and let's say ifc_tools that has all the rest
2. We put all the ifc tools in the FreeCAD base ifc object itself. They all become methods of that object. That would work for now, but later on some stuff will probably not fit there anymore so we'd get back to 1. eventually...

**Comment by yorikvanhavre** [comment]
Ok I did solution 1 above already... I propose to leave it like that until we decide otherwise

**Comment by carlopav** [comment]
Last saturday i was again playing with the code and i pushed another branch with an attempt to refactor the code using a class, but i came to your same conclusion: everything fine until you want to use the importer methods from the FC objects... So, ok! Lets do It this way!

**Pull request closed without merging**
