### PR TITLE
small code changes

### PR DESCRIPTION
**Pull request by berndhahnebach**

### CODE REVIEW

**Comment by berndhahnebach** [comment]
- small code error in README examples

- make sure not to use different types on a method parameter. I took me an hour to find a problem I had because I did not expect the method parameter to take either a list or a ifcopenshell entity instance. Furthermore another method take a ifcos instance but the identifier is calles elements which would be some list or dict but not one instance IMHO. This way it is much more simpler to read the code. If a wrong type will passed an error is raised in get_shape or get_coin. But woud be ok IMHO.

**Comment by berndhahnebach** [comment]
- moveing the iterator out of the get_coin() and get_shape() method makes debug corrupted geometry much simpler ...  

as an example take this problem ... https://github.com/yorikvanhavre/FreeCAD-NativeIFC/issues/28

to test just open the file in nativ importer, it is printed where a problem was, than just ...

```
import ifc_tools
ifc_tools.get_geom_iterator(ifcfile, [ifcfile[39]], True)

```

results in ...

```
>>> 
>>> import ifc_tools
>>> ifc_tools.get_geom_iterator(ifcfile, [ifcfile[39]], True)
  DEBUG: ifc_tools.get_geom_iterator: Invalid iterator
>>> 

```

**Comment by berndhahnebach** [comment]
commit [move getting the geom iterator in separate method](https://github.com/yorikvanhavre/FreeCAD-NativeIFC/pull/29/commits/7bdf9a8571f20f9271fccc4045d5294f35407063)] the filter_elements() is not in the get_geom_iterator() method which means it might needed to be run before manually, but anyway it would help to simplify things ...

**Comment by yorikvanhavre** [comment]
This looks good. But it makes set_geometry not accept lists of elements anymore... Have you checked this works in all scenarios? (Basically both "one object per file" and "each separate ifc  object")

You can run `FreeCAD -t ifc_selftest`

**Comment by berndhahnebach** [comment]
I will have a look at this later this day ... 

BTW: added fix for #28

**Comment by yorikvanhavre** [comment]
Cool!

I wonder if we should not start to think, right from the start, to all these little exceptions because of different platforms, and design a structure where they would all be treated together, rather than spread on all the module...

But that's something for later.

**Pull request merged**
